version: '3.3'

services:
   banco:
     image: mariadb:latest
     volumes:
       - dados_banco:/var/lib/mysql
     restart: always  
     environment:
       MYSQL_ROOT_PASSWORD: senharoot
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: senhawordpress

   wordpress:
     depends_on:
       - banco
     image: wordpress:latest
     ports:
       - "8080:80"
     volumes:
       - .:/var/www/html/wp-content/themes/twentyfifteen
     restart: always
     environment:
       WORDPRESS_DB_HOST: banco:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: senhawordpress
volumes:
   dados_banco:
